import type { Group, GroupColor } from "../shared/model";

export type Language = "zh" | "en";

const zh = {
  locale: "zh-CN",
  title: "Workboard",
  addTask: "新建任务",
  search: "搜索任务或项目",
  allProjects: "全部项目",
  unassigned: "未分配",
  attention: "只看需关注",
  filters: "筛选",
  allStates: "全部状态",
  agentFilter: "Agent 状态",
  requestFilter: "PR / MR 状态",
  filterSummary: "{count} / {total} 个任务 · {filters} 项筛选",
  filterSaveFailed: "筛选已生效，但无法记住条件。请检查客户端存储权限。",
  clearFilters: "清除筛选",
  requestFilters: {
    all: "全部状态",
    none: "未关联",
    open: "开放",
    draft: "草稿",
    merged: "已合并",
    closed: "已关闭",
    unknown: "状态未知",
    "checks-failed": "CI 失败",
    "changes-requested": "需要修改",
    unavailable: "暂不可用",
  },
  quickCreate: "输入标题，Enter 创建",
  quickCreateHint: "仅创建草稿；开始工作时再绑定 workspace。",
  quickCreated: "草稿已创建，可继续输入下一项。",
  quickCreatedHidden: "草稿已创建，当前筛选条件将其隐藏。",
  taskCreated: "草稿已创建。",
  taskUpdated: "任务已更新。",
  taskUpdatedHidden: "任务已更新，当前筛选条件将其隐藏。",
  quickCreateFailed: "未能创建，标题已保留，请重试。",
  attentionReason: "需关注原因",
  attentionActivity: {
    waiting: "Agent 等待输入或权限批准",
    error: "Agent 报错，请打开 workspace 查看",
    attention: "Agent 有未读回复",
  },
  openWorkspace: "打开 workspace",
  pinAutomatic: "Paseo 侧边栏：由 Workboard 自动置顶。离开进行中分组后取消。",
  pinManual: "Paseo 侧边栏：已有或手动置顶，Workboard 不会自动取消。",
  archive: "归档",
  settings: "设置",
  refresh: "刷新",
  save: "保存",
  cancel: "取消",
  working: "正在处理…",
  edit: "编辑",
  notes: "说明",
  details: "展开详情",
  dragTask: "拖动任务到其它阶段",
  dragGroup: "拖动调整分组顺序",
  groupOptions: "分组选项",
  groupLocator: "定位分组",
  collapseColumn: "折叠列",
  expandColumn: "展开列",
  moveGroupLeft: "向左移动",
  moveGroupRight: "向右移动",
  resizeColumn: "调整列宽",
  resizeHint: "拖动调整宽度，双击恢复默认；方向键调整，Home 恢复默认。",
  resetColumnWidth: "恢复默认列宽",
  dropToGroup: "移至：{group} · Esc 取消",
  dropToStart: "移至：{group} · 松手后选择 workspace",
  dropHere: "松手移入此分组",
  dragCancelHint: "Esc 取消",
  groupDragHint: "松手保存分组顺序 · Esc 取消",
  dragChanged: "任务已发生变化，本次拖动已取消。",
  layoutSaveFailed: "无法记住列布局，本次调整仍生效。请检查客户端存储权限。",
  layoutSaved: "分组顺序已保存",
  hideDetails: "收起详情",
  changeRequestStates: {
    open: "开放",
    draft: "草稿",
    merged: "已合并",
    closed: "已关闭",
    unknown: "状态未知",
  },
  checks: { pending: "CI 进行中", success: "CI 通过", failure: "CI 失败" },
  reviews: {
    approved: "评审通过",
    changes_requested: "需要修改",
    pending: "待评审",
  },
  changeRequestUnavailable: "暂时无法获取 MR / PR",
  openChangeRequestError: "无法打开 MR / PR 链接",
  start: "开始工作",
  startHint: "选择项目并创建或关联 workspace。",
  status: "状态",
  create: "创建草稿",
  update: "保存修改",
  titleField: "标题",
  description: "说明（可选）",
  resumeBinding: "继续上次创建或绑定操作，复用同一个 workspace。",
  selectProject: "选择项目",
  newWorkspace: "新建 workspace",
  existingWorkspace: "关联已有 workspace",
  chooseWorkspace: "选择 workspace",
  chooseSource: "选择创建方式",
  directory: "目录",
  worktree: "Git worktree",
  worktreeName: "worktree 名称（可选）",
  noWorkspace: "草稿 · 未创建 workspace",
  noConversation: "尚无对话",
  unknownConversation: "对话时间待核实",
  conversationAtLeast: "不早于 {date}",
  conversationAtMost: "不晚于 {date}",
  expires: "将于 {date} 归档",
  overdue: "已到期，等待检查",
  syncing: "同步中",
  retry: "重试",
  connected: "已连接",
  disconnected: "数据未刷新，写入已暂停",
  loading: "正在载入任务…",
  loadError: "无法读取看板",
  empty: "这里还没有任务",
  emptyFiltered: "没有符合筛选条件的任务",
  conflict: "标签冲突",
  conflictSummary: "{count} 个任务存在标签冲突",
  conflictHint: "为以下任务选择一个分组，修复多个状态标签。",
  resolveConflict: "选择分组",
  archived: "归档记录",
  back: "返回看板",
  archiveDraft: "归档草稿",
  archiveDraftConfirm: "归档草稿“{name}”？归档后将移出看板，目前不支持恢复。",
  autoArchive: "自动归档",
  autoArchiveHint: "完成或废弃且最后对话超过 30 天后，自动归档 workspace。",
  enableAutoArchive: "开启自动归档",
  enableAutoArchiveConfirm:
    "当前有 {count} 个任务已到期。开启后会在安全检查通过时自动归档对应 workspace，可能停止 Agent 和 terminal，并移除托管 worktree。",
  enable: "开启",
  pinInProgressWorkspaces: "进行中任务在 Paseo 侧边栏自动置顶",
  pinInProgressHint:
    "按“进行中”分组判断；离开该分组时仅取消插件添加的置顶，保留你手动置顶的 workspace。",
  settingsTitle: "设置",
  generalSettings: "通用",
  groups: "分组",
  addGroup: "新增分组",
  editGroup: "编辑分组",
  deleteGroup: "删除分组",
  deleteGroupConfirm: "删除分组“{name}”？此操作无法撤销。",
  groupName: "分组名称",
  groupType: "分组类型",
  groupLabel: "Workspace 标签",
  groupLabelPlaceholder: "留空使用 task:分组名称",
  groupColor: "分组颜色",
  groupColorHint: "仅用于看板显示，不改变任务规则或 workspace 标签。",
  groupColors: {
    gray: "灰色",
    blue: "蓝色",
    cyan: "青色",
    teal: "蓝绿色",
    green: "绿色",
    amber: "琥珀色",
    orange: "橙色",
    violet: "紫色",
    pink: "粉色",
    red: "红色",
  } satisfies Record<GroupColor, string>,
  groupsHint:
    "保存或删除分组立即生效，只能删除空分组。至少各保留一个待归类和待开始类型分组，分别接收未标记 workspace 和新草稿。",
  groupSaveFailed: "保存失败，输入已保留。请查看错误提示后重试。",
  groupTypeHints: {
    inbox: "自动接收没有受管理状态标签的 workspace；导入不会写入标签。",
    todo: "接收 Todo 草稿；创建草稿不会创建 workspace 或会话。",
    "in-progress":
      "仅在开启“进行中任务在 Paseo 侧边栏自动置顶”时自动置顶；离开分组时仅取消插件添加的置顶。",
    review: "等待人工验收；Agent 结束不会把任务自动标为完成。",
    done: "开启自动归档后，最后对话超过 30 天且安全检查通过才归档 workspace。",
    canceled:
      "开启自动归档后，最后对话超过 30 天且安全检查通过才归档 workspace；草稿可手动归档。",
  },
  groupTasks: "{count} 个任务",
  defaultGroup: "默认接收草稿",
  defaultWorkspaceGroup: "默认接收未标记 workspace",
  groupNotEmpty: "请先移走任务，再删除分组或修改草稿分组类型。",
  groupDeleteNotEmpty: "分组内还有任务，移走后可删除。",
  groupNeedsTodo: "至少保留一个待开始类型分组。",
  groupNeedsInbox: "至少保留一个待归类类型分组。",
  groupLabelDuplicate: "每个分组必须使用不同的标签。",
  groupInvalid: "请填写有效的分组名称和标签。",
  noStartGroup: "请先在设置中添加一个进行中类型的分组。",
  duePreview: "按当前映射，有 {count} 个已到期任务会在下次检查时处理。",
  mappingPreview: "修改映射会影响 {count} 个已绑定任务。",
  activity: {
    idle: "空闲",
    running: "进行中",
    waiting: "等待输入",
    attention: "需要关注",
    error: "出错",
  },
  stages: {
    inbox: "待归类",
    todo: "待开始",
    "in-progress": "进行中",
    review: "待验收",
    done: "已完成",
    canceled: "已废弃",
  },
  issues: {
    "no-conversation": "尚无对话",
    "conversation-unknown": "对话时间待核实",
    "labels-conflict": "标签冲突",
    "agent-busy": "Agent 仍在工作",
    "terminal-open": "请先关闭 terminal",
    "script-running": "workspace script 仍在运行",
    "git-dirty": "Git 有未提交修改",
    "git-no-upstream": "Git 没有可验证的 upstream",
    "git-unpushed": "Git 有未推送提交",
    "git-detached": "Git 处于 detached HEAD",
    "git-unknown": "无法核实 Git 状态",
    "directory-unavailable": "目录不可用",
    "native-archive-unknown": "归档结果待人工核实",
    "changed-during-check": "检查期间状态已变化",
    "label-sync-incomplete": "标签同步未完成",
  },
  conversationReasons: {
    "replay-timestamp": "Paseo 回放历史时用水合时刻打戳，已改用记录的上下界",
    "truncated-window": "只读取了有限的历史窗口",
    "timeline-unreadable": "时间线读取失败",
    "child-enumeration-unavailable": "无法枚举 provider 子 agent",
    "child-timeline-unreadable": "子 agent 时间线读取失败",
  },
};

const en: typeof zh = {
  locale: "en",
  title: "Workboard",
  addTask: "New task",
  search: "Search tasks or projects",
  allProjects: "All projects",
  unassigned: "Unassigned",
  attention: "Needs attention",
  filters: "Filters",
  allStates: "All states",
  agentFilter: "Agent activity",
  requestFilter: "PR / MR status",
  filterSummary: "{count} / {total} tasks · {filters} filters",
  filterSaveFailed:
    "Filters are applied but could not be remembered. Check client storage permissions.",
  clearFilters: "Clear filters",
  requestFilters: {
    all: "All states",
    none: "Not linked",
    open: "Open",
    draft: "Draft",
    merged: "Merged",
    closed: "Closed",
    unknown: "Unknown state",
    "checks-failed": "CI failed",
    "changes-requested": "Changes requested",
    unavailable: "Unavailable",
  },
  quickCreate: "Task title, Enter to create",
  quickCreateHint:
    "Creates a draft only. Link a workspace when you start work.",
  quickCreated: "Draft created. Add another whenever you are ready.",
  quickCreatedHidden: "Draft created; the current filters hide it.",
  taskCreated: "Draft created.",
  taskUpdated: "Task updated.",
  taskUpdatedHidden: "Task updated; the current filters hide it.",
  quickCreateFailed:
    "Could not create the draft. Your title is kept; try again.",
  attentionReason: "Needs attention because",
  attentionActivity: {
    waiting: "An agent is waiting for input or permission",
    error: "An agent failed; open the workspace to inspect it",
    attention: "An agent has an unread reply",
  },
  openWorkspace: "Open workspace",
  pinAutomatic:
    "Paseo sidebar: automatically pinned by Workboard. Leaving In progress removes this pin.",
  pinManual:
    "Paseo sidebar: existing or manual pin. Workboard will not remove it automatically.",
  archive: "Archive",
  settings: "Settings",
  refresh: "Refresh",
  save: "Save",
  cancel: "Cancel",
  working: "Working…",
  edit: "Edit",
  notes: "Notes",
  details: "Show details",
  dragTask: "Drag task to another stage",
  dragGroup: "Drag to reorder group",
  groupOptions: "Group options",
  groupLocator: "Find group",
  collapseColumn: "Collapse column",
  expandColumn: "Expand column",
  moveGroupLeft: "Move left",
  moveGroupRight: "Move right",
  resizeColumn: "Resize column",
  resizeHint:
    "Drag to resize, double-click to reset. Arrow keys resize; Home resets.",
  resetColumnWidth: "Reset column width",
  dropToGroup: "Move to: {group} · Esc to cancel",
  dropToStart: "Move to: {group} · Release to choose a workspace",
  dropHere: "Release to move into this group",
  dragCancelHint: "Esc to cancel",
  groupDragHint: "Release to save group order · Esc to cancel",
  dragChanged: "The task changed. This drag was canceled.",
  layoutSaveFailed:
    "Could not remember the column layout. This session is updated; check client storage permissions.",
  layoutSaved: "Group order saved",
  hideDetails: "Hide details",
  changeRequestStates: {
    open: "Open",
    draft: "Draft",
    merged: "Merged",
    closed: "Closed",
    unknown: "Unknown state",
  },
  checks: { pending: "CI pending", success: "CI passed", failure: "CI failed" },
  reviews: {
    approved: "Approved",
    changes_requested: "Changes requested",
    pending: "Awaiting review",
  },
  changeRequestUnavailable: "MR / PR information is unavailable",
  openChangeRequestError: "Could not open the MR / PR link",
  start: "Start work",
  startHint: "Choose a project and create or link a workspace.",
  status: "Status",
  create: "Create draft",
  update: "Save changes",
  titleField: "Title",
  description: "Description (optional)",
  resumeBinding: "Resume the previous operation using the same workspace.",
  selectProject: "Select project",
  newWorkspace: "New workspace",
  existingWorkspace: "Link existing workspace",
  chooseWorkspace: "Choose workspace",
  chooseSource: "Choose how to create it",
  directory: "Directory",
  worktree: "Git worktree",
  worktreeName: "Worktree name (optional)",
  noWorkspace: "Draft · no workspace",
  noConversation: "No conversation yet",
  unknownConversation: "Conversation time needs verification",
  conversationAtLeast: "No earlier than {date}",
  conversationAtMost: "No later than {date}",
  expires: "Archives {date}",
  overdue: "Due; waiting for checks",
  syncing: "Syncing",
  retry: "Retry",
  connected: "Connected",
  disconnected: "Data is stale; changes are paused",
  loading: "Loading tasks…",
  loadError: "Could not load the board",
  empty: "No tasks here yet",
  emptyFiltered: "No tasks match these filters",
  conflict: "Label conflict",
  conflictSummary: "Conflicting task labels ({count})",
  conflictHint:
    "Choose one group for each task below to resolve its conflicting status labels.",
  resolveConflict: "Choose group",
  archived: "Archive",
  back: "Back to board",
  archiveDraft: "Archive draft",
  archiveDraftConfirm:
    "Archive draft “{name}”? It will leave the board and cannot currently be restored.",
  autoArchive: "Automatic archive",
  autoArchiveHint:
    "Archive a completed or canceled workspace after 30 days since its last conversation.",
  enableAutoArchive: "Enable automatic archive",
  enableAutoArchiveConfirm:
    "{count} task(s) are currently due. Enabling this will archive their workspaces after safety checks, which may stop agents and terminals and remove managed worktrees.",
  enable: "Enable",
  pinInProgressWorkspaces: "Pin in-progress tasks in the Paseo sidebar",
  pinInProgressHint:
    "Use the In progress group. Leaving it removes only the pin added by this plugin; manually pinned workspaces stay pinned.",
  settingsTitle: "Settings",
  generalSettings: "General",
  groups: "Groups",
  addGroup: "Add group",
  editGroup: "Edit group",
  deleteGroup: "Delete group",
  deleteGroupConfirm: "Delete group “{name}”? This cannot be undone.",
  groupName: "Group name",
  groupType: "Group type",
  groupLabel: "Workspace label",
  groupLabelPlaceholder: "Defaults to task:group-name",
  groupColor: "Group color",
  groupColorHint:
    "Used only on the board. It does not change task rules or workspace labels.",
  groupColors: {
    gray: "Gray",
    blue: "Blue",
    cyan: "Cyan",
    teal: "Teal",
    green: "Green",
    amber: "Amber",
    orange: "Orange",
    violet: "Violet",
    pink: "Pink",
    red: "Red",
  },
  groupsHint:
    "Saving or deleting a group takes effect immediately. Only empty groups can be deleted. Keep an Inbox group for unlabeled workspaces and a To do group for new drafts.",
  groupSaveFailed:
    "Saving failed. Your input is kept; check the error and try again.",
  groupTypeHints: {
    inbox:
      "Receives workspaces without a managed status label. Importing does not write labels.",
    todo: "Receives Todo drafts. Creating a draft creates no workspace or conversation.",
    "in-progress":
      "Pins only when automatic sidebar pinning is enabled. Leaving the group removes only the pin added by this plugin.",
    review:
      "Waits for human acceptance. An agent finishing does not mark the task done.",
    done: "Archives a workspace only when automatic archive is enabled, its last conversation is over 30 days old, and safety checks pass.",
    canceled:
      "Archives a workspace only when automatic archive is enabled, its last conversation is over 30 days old, and safety checks pass. Drafts can be archived manually.",
  },
  groupTasks: "{count} tasks",
  defaultGroup: "Default for drafts",
  defaultWorkspaceGroup: "Default for unlabeled workspaces",
  groupNotEmpty:
    "Move tasks first before deleting the group or changing a draft group's type.",
  groupDeleteNotEmpty: "Move the remaining tasks before deleting this group.",
  groupNeedsTodo: "Keep at least one To do group.",
  groupNeedsInbox: "Keep at least one Inbox group.",
  groupLabelDuplicate: "Each group needs a different label.",
  groupInvalid: "Enter a valid group name and label.",
  noStartGroup: "Add an In progress group in settings before starting work.",
  duePreview:
    "With this mapping, {count} due task(s) will be handled at the next check.",
  mappingPreview: "This mapping affects {count} linked task(s).",
  activity: {
    idle: "Idle",
    running: "Running",
    waiting: "Waiting",
    attention: "Needs attention",
    error: "Error",
  },
  stages: {
    inbox: "Inbox",
    todo: "To do",
    "in-progress": "In progress",
    review: "Review",
    done: "Done",
    canceled: "Canceled",
  },
  issues: {
    "no-conversation": "No conversation yet",
    "conversation-unknown": "Conversation time needs verification",
    "labels-conflict": "Label conflict",
    "agent-busy": "An agent is still working",
    "terminal-open": "Close the terminal first",
    "script-running": "A workspace script is still running",
    "git-dirty": "Git has uncommitted changes",
    "git-no-upstream": "Git has no verifiable upstream",
    "git-unpushed": "Git has unpushed commits",
    "git-detached": "Git is on a detached HEAD",
    "git-unknown": "Could not verify Git state",
    "directory-unavailable": "Directory is unavailable",
    "native-archive-unknown": "Archive result needs manual verification",
    "changed-during-check": "State changed during the check",
    "label-sync-incomplete": "Label sync is incomplete",
  },
  conversationReasons: {
    "replay-timestamp":
      "Paseo stamps replayed history with the hydration moment; recorded bounds are used instead",
    "truncated-window": "Only a bounded history window was read",
    "timeline-unreadable": "The timeline could not be read",
    "child-enumeration-unavailable": "Provider children cannot be listed",
    "child-timeline-unreadable":
      "A provider child's timeline could not be read",
  },
};

export const strings = (language: Language) => (language === "en" ? en : zh);
export function groupTitle(
  group: Group,
  t: ReturnType<typeof strings>,
): string {
  return group.name ?? t.stages[group.kind];
}
export function stageTitle(
  stage: string,
  groups: readonly Group[],
  t: ReturnType<typeof strings>,
): string {
  if (stage === "conflict") return t.conflict;
  const group = groups.find((group) => group.id === stage);
  return group ? groupTitle(group, t) : stage;
}
